### ISSUE TITLE
Titel von Zeitreihen

### ISSUE THREAD

**Issue by SDGlauraschroeder** [G205SDGs/sdg-indicators#109]
1. Aufzählungszeichen am Anfang des Titels

Wollen wir Zeitreihentitel mit "a)" beginnen lassen?
Im Beispiel 6.2.1 handelt es sich dabei nicht um Subindikatoren (in den globalen Metadaten sind keine Subindikatoren genannt, im nationen Metadatenblatt von April 2020 steht, dass die Zeitreihe "a)..." einem Subindikator entsprechen würde...).
Die Zeitreihentitel lauten:
a) Population using safely managed sanitation services
b) Population with a bathtub or a shower

2. Abkürzungen
8.4.1 hat "Raw material consumption (abiotic and biotic material, abbreviation RMC)" als Zeitreihentitel.
Gehören Abkürzungserklärungen in den Zeitreihentitel? Mein Vorschlag in diesem Fall wäre
"Raw material consumption (RMC)" oder einfach nur "Raw material consumption".
Können wir für Abkürzungen im Zeitreihentitel bitte eine Regel zum Vereinheitlichen festlegen?

**Comment by MoBosse** [comment]
@SDGlauraschroeder test

**Comment by WichmannK** [comment]
Zu 1. Können wir aus meiner Sicht gerne löschen. 
Die Nummerierung resultiert noch aus der alten PDF/Excel-Veröffentlichung - als es auch noch keine nationalen Metadaten gab. Hintergrund: Zuordnung zum Buchstaben/Sub-Indikator im Indikatortext oder einfache "Nummerierung" bei verschiedenen Sub-Indikatoren zur besseren Übersichtlichkeit.

Zu 2. Die Bezeichnung zu 8.4.1/12.2.1 und 8.4.2/12.2.2 ist mit Lucia abgestimmt. Sie hat die Bezeichnungen de/en explizit so vorgegeben. Wenn, sollten wir den Punkt auch mit ihr diskutieren.
