### ISSUE TITLE
Zeitreihenlänge

### ISSUE THREAD

**Issue by WichmannK** [G205SDGs/sdg-indicators#120]
Allgemein: Gut wäre, wenn man einzelne Jahre ausblenden könnte - so wie z.B. einzelne Zeitreihen.
 
DNS: Teilweise beginnen Zeitreihen schon 1991. Ich finde dies ehrlich gesagt sehr lang und unausgeglichen zu den übrigen Indikatoren. Die Grafik ist irgendwann nicht mehr gut lesbar. Da aber die Daten nun einmal verfügbar sind, schlage ich vor - sofern technisch möglich - einzelne Jahre bei der Standardansicht auszublenden.

**Comment by moritz** [comment]
vermutlich meinst du einen anderen Moritz als mich :-)
