### ISSUE TITLE
Formulierung "Globale Metadaten"

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#125]
Ich bearbeite gerade den Prüfauftrag von UN-Habitat und beschäftige mich intensiv mit den Indikatoren unter Ziel 11. Ich möchte Euch auf folgendes aufmerksam machen:

Beim Indikator 11.3.1 steht unter dem Punkt "Vergleichbarkeit mit globalen Metadaten" folgender Satz...

Die Zeitreihe “Verhältnis von Flächenver-brauch zu Bevölkerungswachstum (Jahr für Jahr)” entspricht der internationalen Metadatenbeschreibung. Die weiteren drei Zeitreihen liefern zusätzliche Informationen

Muss es in der Konsequenz der Umbenennung in "globale Metadaten" nicht umformuliert werden in...

Die Zeitreihe “Verhältnis von Flächenverbrauch zu Bevölkerungswachstum (Jahr für Jahr)” entspricht den globalen Metadaten. Die weiteren drei Zeitreihen liefern zusätzliche Informationen

**Comment by SDGlauraschroeder** [comment]
Ist erledigt!
