### ISSUE TITLE
3.5.1; hier: Rückmeldung

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#126]
Untenstehend findet Ihr die Rückmeldung von Georg zum Indikator 3.5.1.

Georg schlägt eine Umbenennung der Zeitreihen wie folgt vor:

- Alkohol und andere psychoaktive Sub-stanzen (Alkohol)
   -> ändern in: Alkohol

- Alkohol und andere psychoaktive Sub-stanzen (andere psychoaktive Substan-zen)
   -> ändern in: Andere psychoaktive Sub-stanzen

- Alkohol und andere psychoaktive Sub-stanzen (insgesamt)
   -> keine Änderung

- Drogen
   -> keine Änderung

- Im Metadatenblatt kann beim Link zu den Metadaten der Quelldaten folgendes am Ende des Links gelöscht werden: "?__blob=publicationFile"

**Comment by MoBosse** [comment]
@Taubmann-D @SDGlauraschroeder Könntet ihr bitte prüfen, ob das aktuell ist. Ich meine wir haben in jüngster Vergangenheit die Zeitreihen-/Disaggregationsbenennung angepasst.

**Comment by SDGlauraschroeder** [comment]
- Metadatenblatt mit korrigiertem Link zu den Quelldaten steht online (Stand 24.08.2020)
- Umgestaltung in zwei Zeitreihen:
i) Stationäre Behandlung bei Abhängigkeit (disaggregiert nach Substanz und Geschlecht)
ii) Schätzung des riskanten Konsums (auf Basis von Zugängen zu Behandlung) der Substanzen Opioide, Kokain und anderer Stimulanzien im Alter von 15 bis unter 65 Jahren

-----

Dazu liegt bei mir noch eine Frage aus einem Gespräch mit DT auf dem Tisch:
Die Zeitreihe "Schätzung des riskanten Konsums" ist bisher nur als PDF im Reiter "Weitere Daten" ansehbar. Die Reiter davor heißen "Grafik" und "Tabelle".
--> Könnte man das PDF inhaltlich umstrukturieren (Grafik zuoberst, dann Daten) und die Reiter umbenennen in "Grafik 1", "Tabelle 1", "Grafik 2 und Tabelle 2"?
--> Wäre es evtl. realisierbar die "Schätzung des riskanten Konsums" als Zeitreihe ebenfalls im Auswahlmenü links anzuzeigen - ohne das Daten in der Accessdatenbank stehen - und neben dem Zeitreihennamen zusätzlich auf "Grafik 2 und Tabelle 2" zu verweisen?

**Comment by MoBosse** [comment]
@SDGlauraschroeder 

> --> Könnte man das PDF inhaltlich umstrukturieren (Grafik zuoberst, dann Daten) und die Reiter umbenennen in "Grafik 1", "Tabelle 1", "Grafik 2 und Tabelle 2"?

Das PDF kann man selbstverständlich gestalten, wie man möchte. Eine Umbenennung in "Grafik 1", etc. ist ohne unverhältnismäßig großen Aufwand nur global möglich. D.h. es würde auch bei allen anderen Indikatoren "Grafik 1" heißen, was ich unschön fände...

> --> Wäre es evtl. realisierbar die "Schätzung des riskanten Konsums" als Zeitreihe ebenfalls im Auswahlmenü links anzuzeigen - ohne das Daten in der Accessdatenbank stehen - und neben dem Zeitreihennamen zusätzlich auf "Grafik 2 und Tabelle 2" zu verweisen?

Ich fürchte nicht. Die Auswahlmenüs sind direkt an die Tabelle/Grafik gekoppelt, die nunmal numerische Werte benötigen.

**Comment by MoBosse** [comment]
Da das ursprüngliche Problem (Umbenennung und Disaggregationsstruktur) abgeschlossen scheint, würde ich den Punkt hier schließen. Wenn noch diskussionsbedarf herrscht kann er gerne wieder eröffnet oder ein neues issue erstellt werden.
