### ISSUE TITLE
11.6.1; hier: Datenquelle

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#127]
Ich möchte darauf hinweisen, dass beim Indikator 11.6.1 auf der NRP bei Daten-quelle "Abfallentsorgung - Fachserie 19 Reihe 1 - 2016" angegeben ist. Im natio-nalen Metadatenblatt verweisen wir auf die "Abfallbilanz 2017" – table 1.5 to table 1.12
https://www.destatis.de/DE/Themen/Gesellschaft-Um-welt/Umwelt/Abfallwirtschaft/Publikationen/Downloads-Abfallwirtschaft/abfallbilanz-pdf-5321001.pdf was aus meiner Sicht auch richtig ist.

Bitte prüfen, ggf. ändern und kurze Rück-meldung, wenn Umsetzung erfolgte!

**Comment by SDGlauraschroeder** [comment]
Ist eingepflegt.
