### ISSUE TITLE
3.5.1; hier: Darstellungsvorschlag

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#128]
Bitte verwende die Formulierung aus dem Metadatenblatt:

"Estimate of high risk use (based on treatment entrants) of the substances opioids, cocaine, and other stimulants in the age group 15 to under 65 years"

Stimmt in etwa die deutsche Übersetzung:

"Schätzung des riskanten Konsums (auf der Basis von Zugängen zur Behandlung) der Substanzen Opioide, Kokain und an-dere Stimulanzien in der Altersgruppe der 15- bis unter 65-Jährigen"?

**Comment by SDGlauraschroeder** [comment]
Weiterer Arbeitsauftrag aus der QS-Word-Datei unter diesem Eintrag:

Auf der NRP steht im Englischen als Name der Zeitreihe:
„Estimate of high risk use (based on treatment entrants) of the substances opioids, cocaine and other stimulants in the age group 15 to 65 years“ – das “under” for 65 fehlt.

Das "under" ist nachgetragen.

------------------------

Übersetzung:
Ester Neumeier, die AP für die Zeitreihe beim IFT, schrieb zur englischen Fassung des Titels in ihrer Mail vom 26.05.2020:
"Zum Metadatenblatt haben wir keine weiteren Anmerkungen, das stimmt auf jeden Fall so."
Am 04.05.2020 schrieb Frau Neumeier:
"Die Abbildung zeigt die Daten der "Schätzung riskanten Konsums (auf der Basis von Zugängen zu Behandlung)". Kann dies angepasst oder mit Fußnote ergänzt werden, um Verwechslungen zu vermeiden?"

Damit würde ich die Übersetzung als zufriedenstellend betrachten und den Issue schließen. :)
