### ISSUE TITLE
3.5.1; hier: Link zur Datenquelle 2

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#131]
Zwei Fragen noch: Warum verweisen wir unter Datenquelle auf die Sonderauswer-tung? Die Information steht doch in den nationalen Metadaten. Wird das bei allen Zeitreihen, die auf einer Sonderauswer-tung basieren, so gemacht?

**Comment by Taubmann-D** [comment]
Bitte den Link unter Datenquelle 2 "The time series is a special evaluation based on the Annual Report of the National REITOX Focal Point to the EMCDDA, Work-book Drugs" auf der deutschen Seite ins Deutsche übersetzen z. B. "Bei der Zeitrei-he handelt es sich um eine Sonderauswer-tung auf der Grundlage des Jahresberichts des REITOX-Knotenpunkts an die EMCDDA, Workbook Drogen".

* The time series is a special evaluation based on the Annual Report of the Na-tional REITOX Focal Point to the EMCDDA, Workbook Drugs
* Bei der Zeitreihe handelt es sich um eine Sonderauswertung auf der Grundlage des Jahresberichts des REITOX-Knotenpunkts an die EMCDDA, Workbook Drogen

**Comment by SDGlauraschroeder** [comment]
Ist gemacht.

**Comment by SDGlauraschroeder** [comment]
Ist erledigt.
