### ISSUE TITLE
Nachhaltigkeits-Online Plattformen; hier: Kontaktformular

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#136]
KW: Beim Klick auf Kontakt (englische Version der NRP) gelangt man aktuell auf das deutsche Kontaktformular. Kannst du das bitte überprüfen (vielleicht auch gleich noch für die DNS).
Der Link zum "englischen" Kontaktformu-lar wäre: https://www.destatis.de/EN/Service/Contact/_Contact.html

**Comment by Taubmann-D** [comment]
Ich habe gesehen, dass du den Link zum Kontaktformular auf der NRP (SDGs) korri-giert hast. Kannst du das bitte auch bei der DNS noch abändern?

**Comment by MoBosse** [comment]
Dieser Punkt kann geschlossen werden, da die Links zu den Kontaktformularen im footer durch die funktionalen Mailadressen ersetzt worden sind. 
Allerdings hat dieser Punkt Eingang in open-sdg gefunden. Wen es interessiert: [https://github.com/open-sdg/open-sdg/pull/825](https://github.com/open-sdg/open-sdg/pull/825)

**Comment by Taubmann-D** [comment]
Was heißt das konkret: Allerdings hat dieser Punkt Eingang in open-sdg gefunden. Wen es interessiert: open-sdg/open-sdg#825?

**Comment by MoBosse** [comment]
Ich wollte lediglich darauf hinweisen, dass aufgrund dieses Vorschlags nun in open-sdg vorgesehen ist, dass Links im footer auf die jeweils eingestellte Sprache angepasst werden können.
