### ISSUE TITLE
11.7.1; hier: Sachstand

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#144]
SF: für den SDG-Indikator 11.7.1 haben wir neue Daten (kann ich dir gleich schicken) und auch schon einen Entwurf für das Metadatenblatt vom BKG erhalten, wel-ches uns die neuen Daten bereitstellt. 

Ich bin mir nicht ganz sicher über das weitere Vorgehen; soll ich einfach die Metadaten prüfen, oder gibt es da eine neue Vorlage oder so, die ich verwenden soll? 
Problematisch bei diesem Indikator ist vor allem, dass die Berechnungsmethodik recht aufwendig ist und sich eigentlich nicht in einer Formel darstellen lässt (sie-he Anhang).

**Comment by Taubmann-D** [comment]
LS: Ist gerade in Bearbeitung (26.08.2020)
Metadatenblatt in letzter Abstimmung, Daten wären bereit zum Hochladen auf die Staging Seite (08.09.2020)

**Comment by SDGlauraschroeder** [comment]
Erledigt.
