### ISSUE TITLE
4.1.1; hier: Metadatenblatt 

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#145]
MBo: ich habe mir gerade das Metadatenblatt zu 4.1.1 angeschaut und ein paar Fehler gefunden. Ich habe hier W:\G2\Nachhaltigkeit\international\b_Daten\Indikatoren\SDG 4\4-1-1_MoBo\Metadaten eine neue Version gespeichert, bin mir aber nicht sicher, ob ihr die ganzen Informationen für die Me-tadatenblätter auch noch irgendwo anders abgespeichert habt? Falls ja, gib mir doch mal bitte Bescheid, dann trage ich das da auch noch ein.

**Comment by Taubmann-D** [comment]
LS: überarbeitete Version an MoBo ge-schickt, letzte Abstimmung steht aus (26.08.2020)

**Comment by MoBosse** [comment]
Ich denke das ist erledigt. Falls @SDGlauraschroeder das anders sieht kann er gerne wieder geöffnet werden.
