### ISSUE TITLE
3.1.2; hier: Daten in der globalen Datenbank aus unserer SGD-Online Plattform

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#150]
KW: In der globalen SDG-Datenbank wird unse-re NRP als Quelle beim Indikator 3.1.2 angegeben und somit auch die Daten aus unserem Haus. Das ist super, dass bei diesem Indikator nicht mehr QUAG als Quelle herangezogen wird. Weiß jemand, wie es dazu kam?

**Comment by SDGlauraschroeder** [comment]
DT an LS: Hast Du ggf. noch Schriftwechsel oder E-Mails, wo wir den Sachstand und die weitere Vorgehensweise des Indikators dokumentiert haben? Vielleicht kannst Du Dich auch noch an Einzelheiten erinnern?

------

LS: Wir hatten im Zuge der UNICEF-Abfrage Ende letzten Jahres/Anfang diesen Jahres über den Indikator gesprochen. Ich habe leider keine Mails dazu bei mir gefunden. Ich meine mich zu erinnern, dass wir den Indikator zusammen in deinem Büro besprochen haben. Es gab nur "verlässliche Daten" für Geburten in Krankenhäusern. Die Zahlen auf der Seite des Hebammenverbandes (http://quag.de/quag/geburtenzahlen.htm) bezogen sich auch nur auf Destatis-Zahlen und auf den Daten basierende Schätzungen.
Da du den Indikator damals nur in Vertretung für Kerstin unter deinen Fittichen hattest, wurde nicht viel daran geändert, außer das Metadatenblatt zu aktualisieren und den UNICEF-Fragebogen mit den anderen Referenten zusammen auszufüllen (und dort dann die Zahlen von QUAG mit unseren zu ersetzen und unsere NRP als Quelle anzugeben).

In Bezug auf die Mail an Kerstin: Außer diesem Kontakt gab es keine Kommunikation mit UNICEF. Ich vermute, dass das Ausfüllen des Fragebogens zum Ändern der Quelle in der globalen SDG-Datenbank geführt hat?
