### ISSUE TITLE
9.1.2; hier: Disaggregation

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#157]
könntest Du (in Rücksprache mit Georg) bitte 

-> "Transport in Rohrleitungen: Rohöl" ändern in
-> "Rohrfernleitungen: Rohöl".

Vgl. Fachserie 8  Reihe 1.1; hier: 1.6 Rohrfernleitungen

**Comment by MoBosse** [comment]
@Taubmann-D Gibt es dazu auch eine englische Übersetzung? Dann kann ich das in einem Abwasch einfügen.

**Comment by Taubmann-D** [comment]
Hola nach Bonn (Georg),

hast Du für unten stehende Begrifflichkeit (als Indikatorenverantwortlicher) eine englische Übersetzung für die SDG-Online Plattform?

Vielen Dank und viele Grüße
Doreen

**Comment by Taubmann-D** [comment]
Hallo Doreen,

ich bin für "pipelines: crude oil"

Viele Grüße
Georg

**Comment by MoBosse** [comment]
Tut mir leid, ich muss leider noch einmal nachfragen: Auf was hatten wir uns bezüglich der Kategorie geeinigt? Verkehrsträger oder Wirtschaftszweig? Ich finde meine Notizen leider nicht mehr. Sorry.

**Comment by WichmannK** [comment]
Hallo Moritz, es war Verkehrsträger - analog zur deutschen Indikatorbezeichnung.

-----Ursprüngliche Nachricht-----
Von: Moritz Bosse <notifications@github.com> 
Gesendet: Montag, 9. November 2020 15:22
An: G205SDGs/sdg-indicators <sdg-indicators@noreply.github.com>
Cc: Wichmann, Kerstin (G205) <Kerstin.Wichmann@destatis.de>; Assign <assign@noreply.github.com>
Betreff: [EXTERN]Re: [G205SDGs/sdg-indicators] 9.1.2; hier: Disaggregation (#157)

Tut mir leid, ich muss leider noch einmal nachfragen: Auf was hatten wir uns bezüglich der Kategorie geeinigt? Verkehrsträger oder Wirtschaftszweig? Ich finde meine Notizen leider nicht mehr. Sorry.

**Comment by MoBosse** [comment]
Ist auf der Staging Seite und wird beim nächsten upload auch auf die Live-Seite übertragen.
