### ISSUE TITLE
3.1.e; hier: Ergänzung "Geschlecht"

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#158]
ich wurde heute von Frau Dr. Jozefini (BMG) darauf hingewiesen, dass bei oben genanntem Indikator auf der Dialogfassung keine Auswahl nach "Geschlecht" möglich ist.

In Rücksprache mit Sven bitte ich Dich, beim Indikator 3.1.e auf der Dialogfassung (https://dns-dialogfassung.github.io//3-1-e/) schnellstmöglichst als weitere Auswahlmöglichkeit neben der Altersklasse das Geschlecht zu ergänzen.

Dies war ein Wunsch des BMG (vgl. beigefügte E-Mail) und wurde von uns zugesagt.

Bitte gib mir ein Zeichen, wenn Du die Änderung hochgeladen hast, damit ich Frau Dr. Jozefini Bescheid geben kann.

**Comment by MoBosse** [comment]
Erledigt
