### ISSUE TITLE
Regionale Gliederung

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#162]
Hallo Moritz,

wie heute Morgen mit Dir und Kerstin besprochen, habe ich mich auf die Suche nach einem Begriff für "Bundesland" gemacht.

Beigefügt findest Du die Bezeichnung in der GBE (Region) und Genesis (Bundesländer). In Rücksprache mit Kerstin plädieren wir für den Begriff "Region". Was meinst Du?

Wenn wir bei der Auswahl "Bundesland" durch "Region" ersetzen, bitte auch an die Indikatoren denken wo "Gebiet" steht. Wir sollten dann auch Gebiet durch "Region" ersetzen.

Vielen Dank und viele Grüße
Doreen

**Comment by MoBosse** [comment]
Ist auf allen drei Seiten (DNS, DNS-Dialog & SDG) geändert oder wird bei der nächsten Aktualisierung geändert.
