### ISSUE TITLE
Einheitliche Begriffsverwendung "Auswahl" anstatt "Disaggregation"

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#163]
Lieber Moritz,

in der Anlage habe ich beispielhaft jeweils einmal die Bezeichnung auf der DNS-Online Plattform (Disaggregation) und auf der SDG-Online Plattform (Auswahl) visualisiert. Da ich den Begriff "Disaggregation" nicht nutzerfreundlich finde und wir dieses Thema im Rahmen der SDG-Online Plattform bereits diskutiert und umgesetzt haben, bitte ich Dich, auf der DNS-Online Plattform den Begriff "Disaggregation" durch "Auswahl" zu ersetzen.

Vielen Dank und viele Grüße
Doreen

**Comment by MoBosse** [comment]
Erledigt
