### ISSUE TITLE
Statusänderung

### ISSUE THREAD

**Issue by Taubmann-D** [G205SDGs/sdg-indicators#165]
Lieber Moritz,

bitte ändere bei nachfolgenden (zwei) Indikatoren den Status:

Indikator 2.1.1: Prävalenz von Unterernährung
-> von "in Bearbeitung" in "Datenquellenanalyse"

Indikator 16.1.2: Konfliktbezogene Todesfälle je 100 000 Einwohner, nach Geschlecht, Alter und Todesursache
-> von "nicht zutreffend" in "Datenquellenanalyse"

Vielen Dank und viele Grüße
Doreen

**Comment by MoBosse** [comment]
Erledigt
