### ISSUE TITLE
Anmerkungen auf der NRP (unter der Grafik)

### ISSUE THREAD

**Issue by SDGlauraschroeder** [G205SDGs/sdg-indicators#172]
Grundlage:
KW: "Rectified" wird in der amtlichen Statistik nicht verwendet, sondern "revised".

Entscheidung von Sven dazu steht aus.

Je nachdem, müssten alle Indikatoren mit diesem Begriff in der Anmerkung entsprechend geändert werden.

Eventuell betrifft das Problem auch die DNS.

**Comment by SDGlauraschroeder** [comment]
Im Internen Glossar Stat. Fachbegriffe wird rectified nicht erwähnt. Dort gibt es nur revised.

Telefonat mit SK am 05.11.2020:
Er hat rectified noch nicht gehört, findet die Bedeutung aber auch zutreffend. Seinem Sprachgefühl nach gibt es einen Unterschied zwischen "rectified" und "revised". Allerdings kostet es uns extra Zeit, darüber jedes Mal Gedanken zu machen, daher seine Entscheidung: Alles bitte zu "revised" gleichmachen.

**Comment by Taubmann-D** [comment]
Aus meinem früheren fachstatistischen Verständnis gibt es einen Unterschied zwischen "korrigiert" und "revidiert". In der Fachstatistik haben wir, wenn z. B. in der Fachserie ein Wert falsch veröffentlicht wurde, korrigiert. Im Haus gibt es hierzu eine "Richtlinie zum Umgang mit Veröffentlichungsfehlern (VÖFe-Richtlinie)" (https://intranet.stba.doi-de.net/DE/LeitungPlanung/Qualitaet/Datenqualitaet/FRRichtlinieAlllgemein.html). Demgegenüber gibt es statistikübergreifende Grundsätze zur Revision von veröffentlichten statistischen Ergebnissen (https://stanet-web.stba.testa-de.net/DE/Statistikuebergreifend/Qualitaetsmanagement/AllgemRevisionspolitik.pdf;jsessionid=6E049070832A6924C5863E9E6C9FD4CA.StanetLive1?__blob=publicationFile). Da habe ich leider keine Erfahrungen.

Wir müssen entscheiden, ob und wie wir auf den Online Plattformen "korrigierte" und "revidierte" Werte kennzeichnen wollen. Vielleicht reicht es ja, wenn wir anmerken, dass die Werte "geändert" wurden. Der Datenhalter, der die Verantwortung für die Daten hat, weiß (bei Rückfrage durch die Nutzerinnen und Nutzer) auf jeden Fall, ob seine Werte "korrigiert" oder "revidiert" wurde.
