### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by WohnungNDS** [G205SDGs/sdg-indicators#229]
@moBosse

Hello, 
something is wrong with your map in http://sdg-indikatoren.de/5-5-1/

**Comment by MoBosse** [comment]
Hi @WohnungNDS Thank you for the hint. I wonder if it might fail because I have some rows without data in my csv. I will test this and let you know.

**Comment by MoBosse** [comment]
I think it failed to build the maps because I forgot to update the [requirements](https://github.com/G205SDGs/sdg-data/pull/117/files#diff-7a3ce58e9448657fa8ab45e91f4cd0ad00ddb48e18e9fdca941aa56ac1b15c2dR6) in the data repo.
Thanks again @WohnungNDS
